{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "miles-workbench.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "miles-workbench.labels" . | nindent 4 }}
rules:
  {{- include "miles-workbench.roleRules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "miles-workbench.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "miles-workbench.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "miles-workbench.fullname" . | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "miles-workbench.serviceAccountName" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
