{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miles-workbench.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "miles-workbench.labels" . | nindent 4 }}
{{- end }}
