from model_args_utils import moe_layer_freq


def model_args(nlayers: int = 45, first_k_dense_replace: int = 3) -> str:
    return (
        "--spec miles_plugins.models.glm5_next.glm5_next get_glm5_next_spec "
        f"--num-layers {nlayers} "
        "--hidden-size 4096 "
        "--ffn-hidden-size 12288 "
        "--num-attention-heads 64 "
        "--multi-latent-attention "
        "--q-lora-rank 1536 "
        "--kv-lora-rank 512 "
        "--qk-head-dim 256 "
        "--qk-pos-emb-head-dim 0 "
        "--v-head-dim 256 "
        "--kv-channels 256 "
        "--qk-layernorm "
        f"--moe-layer-freq {moe_layer_freq(nlayers=nlayers, first_k_dense_replace=first_k_dense_replace)} "
        "--num-experts 288 "
        "--moe-router-topk 8 "
        "--moe-router-score-function sigmoid "
        "--moe-router-pre-softmax "
        "--moe-router-enable-expert-bias "
        "--moe-router-bias-update-rate 0 "
        "--moe-router-topk-scaling-factor 2.5 "
        "--moe-ffn-hidden-size 2048 "
        "--moe-shared-expert-intermediate-size 2048 "
        "--moe-router-dtype fp32 "
        "--moe-grouped-gemm "
        "--moe-permute-fusion "
        "--vocab-size 154880 "
        "--rotary-base 10000 "
        "--rope-type rope "
        "--no-rope-fusion "
        "--position-embedding-type rope "
        "--normalization RMSNorm "
        "--norm-epsilon 1e-5 "
        "--swiglu "
        # the checkpoint sets swiglu_limit=10, which sglang applies to dense, shared and routed MLPs
        "--activation-func-clamp-value 10 "
        "--disable-bias-linear "
        "--untie-embeddings-and-output-weights "
        "--make-vocab-size-divisible-by 16 "
        "--enable-experimental "
    )
